#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.xyz"
EWW="$HOME/clones/eww/target/release/eww -c $HOME/.config/eww/"


if [ "$1" == "init" ]; then 
  rm "$FILE"
fi
## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	${EWW} open --screen 0 bar
        
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww && bspc config -m LVDS-1 top_padding 49
else
	${EWW} close-all && killall eww
	rm "$FILE"
fi
